from __future__ import annotations

import getpass
import html
import importlib.metadata
import json
import re
import struct
import sys
import zlib
from datetime import datetime, timezone
from pathlib import Path

import altair as alt

_REPORT_PREFIX = "dysonsphere-report-"


# ── Writing metadata into output files ───────────────────────────────────────


def _inject_png_metadata(png_bytes: bytes, text: str, keyword: str = "Description") -> bytes:
    """Insert an iTXt chunk (``keyword`` → ``text``) immediately after the IHDR chunk.

    Used for both the human-readable ``Description`` and the machine-readable
    ``dysonsphere`` JSON payload.  iTXt supports UTF-8 text (unlike tEXt which is
    Latin-1 only).  The chunk is inserted after IHDR so metadata-aware readers
    encounter it before any pixel data.  All existing chunks and their CRCs are left
    unchanged; only the new chunk's CRC is computed here.
    """
    chunk_type = b"iTXt"
    data = (
        keyword.encode("latin-1")
        + b"\x00"  # keyword + null terminator
        + b"\x00"  # compression flag: 0 (uncompressed)
        + b"\x00"  # compression method: 0
        + b"\x00"  # language tag: empty + null
        + b"\x00"
        + text.encode("utf-8")  # translated keyword: empty + null + text
    )
    crc = zlib.crc32(chunk_type + data) & 0xFFFFFFFF
    chunk = struct.pack(">I", len(data)) + chunk_type + data + struct.pack(">I", crc)

    # Locate end of IHDR: signature(8) + length(4) + type(4) + data(ihdr_len) + crc(4)
    ihdr_data_len = struct.unpack(">I", png_bytes[8:12])[0]
    insert_at = 8 + 4 + 4 + ihdr_data_len + 4

    return png_bytes[:insert_at] + chunk + png_bytes[insert_at:]


def _render_provenance(prov: dict) -> str:
    """Render the structured provenance dict as a human-readable ``report.provenance``
    section (title + underline + a 'Generated by …' sentence), matching the statistics
    report style so the sections read as one document when joined.
    """
    title = "Provenance"
    sentence = (
        f"Generated by {prov['user']} with {prov['script']} on {prov['timestamp']} "
        f"using Python {prov['python']}, Altair {prov['altair']}, dysonsphere {prov['dysonsphere']}."
    )
    return f"{title}\n{'─' * len(title)}\n\n{sentence}"


def _build_provenance() -> dict:
    """Collect the generation facts (user, script, timestamp, versions) for the block."""
    try:
        _shell = get_ipython().__class__.__name__  # ty: ignore[unresolved-reference]
        script = "<jupyter-notebook>" if _shell == "ZMQInteractiveShell" else "<ipython>"
    except NameError:
        script = Path(sys.argv[0]).name or "<unknown-script>"
    try:
        user = getpass.getuser()
    except Exception:
        user = "unknown_user"
    return {
        "user": user,
        "script": script,
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "python": sys.version.split()[0],
        "altair": alt.__version__,
        "dysonsphere": importlib.metadata.version("dysonsphere"),
    }


def _build_block(records: list, *, embed_report: bool) -> tuple[dict, str, dict[str, str] | None]:
    """Assemble the ``dysonsphere`` metadata block from the drained statistical records.

    Returns ``(usermeta, usermeta_json, report_sections)``:

    - ``usermeta`` — ``{"dysonsphere": {provenance, statistics?, theme, report?}}`` for the
      Vega-Lite JSON ``usermeta`` (the ``report`` member is nested here).
    - ``usermeta_json`` — the structured block *without* ``report``, serialized for the SVG
      ``<metadata>`` / PNG iTXt (those carry the report in dedicated readable channels).
    - ``report_sections`` — ``{section: text}`` (``statistics`` when there are records +
      ``provenance`` always), or ``None`` when ``embed_report`` is off.

    ``theme`` holds the resolved ``ds.theme()`` args (only ``_BUILTIN_DEFAULTS`` keys, so
    every one is a valid kwarg — dysonsphere params, never Altair's), letting ``load()``
    reconstruct the styling via ``ds.theme(**theme)``.
    """
    from .statistics import _render_report
    from .theme import _BUILTIN_DEFAULTS

    provenance = _build_provenance()
    ds_block: dict = {"provenance": provenance}
    if records:
        ds_block["statistics"] = records
    ds_block["theme"] = {k: v for k, v in alt.theme.options.items() if k in _BUILTIN_DEFAULTS}
    usermeta = {"dysonsphere": ds_block}
    # Serialized before `report` is attached, so the SVG/PNG structured blob stays report-free
    # (they instead get per-section readable channels).  ensure_ascii=False keeps η²/─ literal.
    usermeta_json = json.dumps(ds_block, ensure_ascii=False)
    report_sections: dict[str, str] | None = None
    if embed_report:
        report_sections = {}
        if records:
            report_sections["statistics"] = "\n\n".join(_render_report(r) for r in records)
        report_sections["provenance"] = _render_provenance(provenance)
        ds_block["report"] = report_sections  # rides only in the JSON usermeta (nested member)
    return usermeta, usermeta_json, report_sections


def _svg_inserts(usermeta_json: str | None, report_sections: dict[str, str] | None, description: str | None) -> str:
    """Build the string injected after the opening ``<svg>`` tag: the structured
    ``<metadata id="dysonsphere">`` (CDATA), one readable ``<metadata id="dysonsphere-report-
    <section>">`` per section, and the user's ``<desc>``.  Empty when nothing to embed.
    """
    out = ""
    if usermeta_json is not None:
        out += f'<metadata id="dysonsphere"><![CDATA[{usermeta_json}]]></metadata>'
    if report_sections is not None:
        for section, text in report_sections.items():
            out += f'<metadata id="dysonsphere-report-{section}">{html.escape(text)}</metadata>'
    if description is not None:
        out += f"<desc>{html.escape(description)}</desc>"
    return out


def _inject_png_block(
    png_bytes: bytes, usermeta_json: str | None, report_sections: dict[str, str] | None, description: str | None
) -> bytes:
    """Inject the user ``Description``, the structured ``dysonsphere`` chunk, and one
    ``dysonsphere-report-<section>`` chunk per report section into the PNG.
    """
    if description is not None:
        png_bytes = _inject_png_metadata(png_bytes, description)
    if usermeta_json is not None:
        png_bytes = _inject_png_metadata(png_bytes, usermeta_json, keyword="dysonsphere")
    if report_sections is not None:
        # _inject_png_metadata prepends (each chunk lands right after IHDR), so inject in
        # reverse to leave the sections in section order — matching the JSON/SVG.
        for section, text in reversed(report_sections.items()):
            png_bytes = _inject_png_metadata(png_bytes, text, keyword=f"{_REPORT_PREFIX}{section}")
    return png_bytes


# ── Reading metadata back ────────────────────────────────────────────────────


def _iter_png_itxt(png_bytes: bytes):
    """Yield ``(keyword, text)`` for every PNG ``iTXt`` chunk."""
    i = 8  # skip the 8-byte PNG signature
    while i + 8 <= len(png_bytes):
        length = int.from_bytes(png_bytes[i : i + 4], "big")
        ctype = png_bytes[i + 4 : i + 8]
        chunk = png_bytes[i + 8 : i + 8 + length]
        if ctype == b"iTXt":
            kw, rest = chunk.split(b"\x00", 1)
            # keyword\0 + compflag/method/lang/transkw nulls + text
            yield kw.decode("utf-8"), rest.lstrip(b"\x00").decode("utf-8")
        if ctype == b"IEND":
            break
        i += 12 + length


def _read_png_text(png_bytes: bytes, keyword: str) -> str | None:
    """Return the UTF-8 text of the PNG ``iTXt`` chunk with ``keyword`` (or None)."""
    return next((t for kw, t in _iter_png_itxt(png_bytes) if kw == keyword), None)


def _read_dysonsphere_block(path: str) -> dict:
    """Read the embedded ``usermeta.dysonsphere`` block from a dysonsphere-exported PNG,
    SVG, or Vega-Lite JSON (detected by extension), as the unified
    ``{provenance, statistics, theme, report}`` dict.  For SVG/PNG the ``report`` container
    (whose sections ride in their own readable channels) is merged back in.  Raises if none
    is found.
    """
    p = Path(path)
    ext = p.suffix.lower()
    if ext == ".json":
        block = (json.loads(p.read_text(encoding="utf-8")).get("usermeta") or {}).get("dysonsphere")
    elif ext == ".svg":
        svg = p.read_text(encoding="utf-8")
        m = re.search(r'<metadata id="dysonsphere"><!\[CDATA\[(.*?)\]\]></metadata>', svg, re.DOTALL)
        block = json.loads(m.group(1)) if m else None
        sections = {
            sec: html.unescape(txt)
            for sec, txt in re.findall(r'<metadata id="dysonsphere-report-([^"]+)">(.*?)</metadata>', svg, re.DOTALL)
        }
        if block is not None and sections:
            block["report"] = sections
    elif ext == ".png":
        data = p.read_bytes()
        struct_text = _read_png_text(data, "dysonsphere")
        block = json.loads(struct_text) if struct_text is not None else None
        sections = {kw[len(_REPORT_PREFIX) :]: t for kw, t in _iter_png_itxt(data) if kw.startswith(_REPORT_PREFIX)}
        if block is not None and sections:
            block["report"] = sections
    else:
        raise ValueError(f"read() supports .png, .svg, or .json files, got {p.suffix!r}")
    if block is None:
        raise ValueError(f"no dysonsphere metadata found in {path!r} — was it saved by ds.save()?")
    return block


def read(path: str, *, what: str = "report", save: bool | str = False) -> "str | list | dict":
    """Read back the metadata embedded by :func:`save` from a PNG, SVG, or Vega-Lite JSON.

    Parameters
    ----------
    path:
        A dysonsphere-exported ``.png``, ``.svg``, or ``_vegalite.json`` file.
    what:
        Which artifact to return:

        - ``'report'`` (default) — the human-readable report **table** as a ``str``;
          it is printed to stdout and returned. Joins every section of the ``report``
          container (``statistics`` + ``provenance``). Falls back to re-rendering the
          statistics from the embedded records if the prose wasn't saved
          (``embedReport=False``).
        - ``'statistics'`` — the structured **records** (list of dicts, exact floats).
        - ``'metadata'`` — the whole ``{provenance, statistics, theme, report}`` dict, where
          ``report`` is the ``{section: text}`` container.
    save:
        Only for ``what='report'``: ``True`` writes the report to a ``.txt`` in the cwd;
        a string writes to that directory.
    """
    block = _read_dysonsphere_block(path)
    if what == "metadata":
        return block
    if what == "statistics":
        return block.get("statistics", [])
    if what != "report":
        raise ValueError(f"what must be 'report', 'statistics', or 'metadata', got {what!r}")
    report = block.get("report")  # {section: text} container
    if report:
        text = "\n\n".join(report.values())
    else:  # prose wasn't embedded (embedReport=False) — re-render from records
        from .statistics import _render_report

        text = "\n\n".join(_render_report(r) for r in block.get("statistics", []))
    print(text)
    if save:
        directory = Path(save) if isinstance(save, str) else Path.cwd()
        directory.mkdir(parents=True, exist_ok=True)
        ts = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
        (directory / f"dysonsphere_report_{ts}.txt").write_text(text + "\n", encoding="utf-8")
    return text
